development:
  adapter: mysql2
  encoding: utf8
  database: stock_dev
  host: localhost
  username: stock_dev
  password: dreamology

test:
  adapter: mysql2
  encoding: utf8
  database: stock_dev
  host: localhost
  username: stock_dev
  password: dreamology

production:
  adapter: mysql2
  encoding: utf8
  database: stock
  host: localhost
  username: stock
  password: dreamology